version: "3"

services:

  personal-avito:
    container_name: personal-avito
    restart: always
    image: postgres
    ports:
      - 5432:5432
    env_file:
      - ./.env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - personal-avito-postgresql-data:/var/lib/postgresql/data/

volumes:
 personal-avito-postgresql-data: