version: "3"

services:

  db-personal-avito:
    container_name: db-personal-avito
    restart: always
    image: postgres
    ports:
      - 5432:5432
    env_file:
      - ./.env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - db-personal-avito-postgresql-data:/var/lib/postgresql/data/

  run-migration:
    container_name: run-migration
    build:
      dockerfile: ./Dockerfile
      context: ./
    command: bash -c "alembic upgrade head"
    ports:
      - 8001:8000
    volumes:
      - run-migration-data:/run-migration-data

  personal-avito:
    container_name: personal-avito
    build:
      dockerfile: ./Dockerfile
      context: ./
    ports:
      - 8000:8000
    volumes:
      - personal-avito-data:/personal-avito-data



volumes:
 db-personal-avito-postgresql-data:
 run-migration-data:
 personal-avito-data:
 

