"""New table complaint

Revision ID: 3afb266ec507
Revises: ef5b2d8bf0d0
Create Date: 2023-03-15 15:52:14.531877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3afb266ec507'
down_revision = 'ef5b2d8bf0d0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('complaint_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('advertisement_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('date_of_create', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['advertisement_id'], ['advertisement_table.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.id'], ),
    sa.PrimaryKeyConstraint('id', 'advertisement_id', 'user_id')
    )
    op.create_index(op.f('ix_complaint_table_id'), 'complaint_table', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_complaint_table_id'), table_name='complaint_table')
    op.drop_table('complaint_table')
    # ### end Alembic commands ###
