"""l

Revision ID: 6a3ddc59f45f
Revises: 777352f7a19f
Create Date: 2023-03-15 11:52:38.083163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a3ddc59f45f'
down_revision = '777352f7a19f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_table', sa.Column('iii', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_table', 'iii')
    # ### end Alembic commands ###
