"""l

Revision ID: 777352f7a19f
Revises: 
Create Date: 2023-03-15 11:02:45.696836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '777352f7a19f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    advertisement_group_table = op.create_table('advertisement_group_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    role_table = op.create_table('role_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('second_name', sa.String(), nullable=True),
    sa.Column('date_of_registration', sa.DateTime(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('time_zone', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role_table.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login')
    )
    op.create_table('advertisement_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('date_of_publication', sa.String(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['advertisement_group_table.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_advertisement_table_id'), 'advertisement_table', ['id'], unique=False)
    op.create_table('feedback_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('advertisement_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('rate', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['advertisement_id'], ['advertisement_table.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.id'], ),
    sa.PrimaryKeyConstraint('id', 'advertisement_id', 'user_id')
    )
    op.create_index(op.f('ix_feedback_table_id'), 'feedback_table', ['id'], unique=False)
    op.bulk_insert(advertisement_group_table, [{'id':1, 'group_name':'Immovable property'}])
    op.bulk_insert(advertisement_group_table, [{'id':2, 'group_name':'Car'}])
    op.bulk_insert(advertisement_group_table, [{'id':3, 'group_name':'Technique'}])
    op.bulk_insert(advertisement_group_table, [{'id':4, 'group_name':'Furniture'}])
    op.bulk_insert(role_table, [{'id':1, 'name':'User'}])
    op.bulk_insert(role_table, [{'id':2, 'name':'Admin'}])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feedback_table_id'), table_name='feedback_table')
    op.drop_table('feedback_table')
    op.drop_index(op.f('ix_advertisement_table_id'), table_name='advertisement_table')
    op.drop_table('advertisement_table')
    op.drop_table('user_table')
    op.drop_table('role_table')
    op.drop_table('advertisement_group_table')
    # ### end Alembic commands ###
